### ISSUE TITLE
ContentProvider 代理

### ISSUE THREAD

**Issue by lcrjeff** [tiann/understand-plugin-framework#1]
大神，怎么实现代理ContentProvider呢

**Comment by tiann** [comment]
请关注我的下一篇文章 ^ ^

**Comment by lcrjeff** [comment]
好的

**Comment by zouguibao** [comment]
这个不会再更新了吗？

**Comment by tiann** [comment]
会更新，草稿已出；只是业务比较繁忙，时间不太充足，所以比较慢。

**Comment by zouguibao** [comment]
如何自己实现Binder服务这块能否给出点思路或者是讲解，除了AIDL其他的貌似都没有思路

**Comment by tiann** [comment]
@zouguibao Binder服务不过是一个Binder的宿主而已，Service以及Provider都可以成为这个角色；Service的onBind方法可以直接返回IBinder，Provider需要想办法传递IBInder，一般来说call方法就可以；
由于组件的特殊性，Service的IBinder服务是异步的，Provider是同步的。

**Comment by tiann** [comment]
参考 contentprovider-management模块，详细解释见 [Android插件化原理解析——ContentProvider的插件化](http://weishu.me/2016/07/12/understand-plugin-framework-content-provider/)
