### ISSUE TITLE
三星Galaxy Note5 6.0系统手机binder hook无效

### ISSUE THREAD

**Issue by MrDreamCacher** [tiann/understand-plugin-framework#12]
你好，我使用三星 6.0系统的手机测试剪贴板的demo没有效果，不知道是什么原因。

**Comment by tiann** [comment]
有日志吗？

**Comment by MrDreamCacher** [comment]
我使用6.0、7.0的模拟器运行可以hook成功，猜测三星的机器系统做了处理。
出错日志：
07-12 14:46:43.691 24785-24785/com.weishu.binder_hook.app E/ClipboardServiceEx: clipEx is android.sec.clipboard.ClipboardExManager@6bd8b9e
07-12 14:46:43.691 24785-24785/com.weishu.binder_hook.app E/ClipboardServiceEx: clipEx has text data : false

**Comment by tiann** [comment]
@MrDreamCacher 嗯，看日志是三星做了处理。这是个demo用来理解插件方案的，并非能直接投入生产环境中使用；你可以反编译下三星的代码，看看它做了什么处理。
