### ISSUE TITLE
classloader-hook部分的问题

### ISSUE THREAD

**Issue by jhwsx** [tiann/understand-plugin-framework#13]
采用激进方案：Hook掉ClassLoader方法时,不使用hookPackageManager()方法时,并没有出现文章中所说的`java.lang.RuntimeException: Unable to start activity ComponentInfo {com.weishu.upf.ams_pms_hook.app/com.weishu.upf.ams_pms_hook.app.MainActivity}: java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.IllegalStateException: Unable to get package info for com.weishu.upf.ams_pms_hook.app; is package not installed?`异常.

**Comment by tiann** [comment]
一个手机上测试可行不代表别的就可行
