### ISSUE TITLE
ams-pms的hook会调用多次

### ISSUE THREAD

**Issue by nangonghuang** [tiann/understand-plugin-framework#15]
第一次进去是正常的，退出程序后再进去，点一下就hook两次，再退出再进去，点一下hook三次，不知道什么原因。。

**Comment by tiann** [comment]
你的退出可能并没有完全退出进程。另外，这只是一个拿来讲解的demo，并不具备实际用途。

**Comment by nangonghuang** [comment]
我找到原因了。。是因为再次进去又hook了一次，需要在onDestroy里面还原回去。。
主要还是在Activity那个demo里面，退出去再进app会崩溃，然后加了个null判断之后再点会出现还是调subActivity的情况，原因和这里是一样的。
不过demo能直接跑起来就已经很满意了
不知道什么时候更新后面的内容，这个系列好精彩

**Comment by tiann** [comment]
不会再更新了 :)  插件化已经落幕

**Comment by MrLiKH** [comment]
为什么说插件化已经落幕啦
