### ISSUE TITLE
hook classloader失败

### ISSUE THREAD

**Issue by e-snail** [tiann/understand-plugin-framework#3]
用LoadedApkClassLoaderHookHelper.hookLoadedApkInActivityThread来替换自定义的classloader，没有提示任何异常。然后使用在其它地方取得context的classloader，发现它仍然是原来的，不是自定义的。

何解？

**Comment by tiann** [comment]
两个方法的调用时机是正确的吗？

**Comment by e-snail** [comment]
就是用的你的代码

**Comment by jhwsx** [comment]
在开启插件Activity时,intent增加 intent.putExtra("target", true);
在IActivityManagerHandler类中,
` @Override
    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
//        Log.d(TAG, "method: " + method.getName());
//        ActivityManagerService类中的startActivity()方法
//        public final int startActivity(IApplicationThread caller, String callingPackage,
//                Intent intent, String resolvedType, IBinder resultTo, String resultWho, int requestCode,
//        int startFlags, ProfilerInfo profilerInfo, Bundle options)
        if ("startActivity".equals(method.getName())) {
            // 获取intent参数的索引
            int intentArgsIndex = -1;
            for (int i = 0; i < args.length; i++) {
                if (args[i] instanceof Intent) {
                    intentArgsIndex = i;
                    break;
                }
            }
            // 取出rawIntent
            Intent rawIntent = (Intent) args[intentArgsIndex];
            // 只有是调取插件apk的入口时才进行替换
            **if (rawIntent.getBooleanExtra("target", false)) {**
                // 构造替换的Intent
                Intent stubIntent = new Intent();
                String stubPackage = UPFApplication.getContext().getPackageName();
                stubIntent.setComponent(new ComponentName(stubPackage, StubActivity.class.getName()));
                stubIntent.putExtra("target", true);
                stubIntent.putExtra(AMSHookHelper.EXTRA_TARGET_INTENT, rawIntent); // 保存真正要启动的intent

                // 替换intent
                args[intentArgsIndex] = stubIntent;
            }

            return method.invoke(mBase, args);
        }
        return method.invoke(mBase, args);
    }`
加上if (rawIntent.getBooleanExtra("target", false))条件判断,保证只有是调取插件apk的入口时才进行intent的替换,如果已经调取插件,插件内部的页面跳转,就不再替换intent了.

**Comment by tiann** [comment]
@jhwsx 貌似跟本issue没有什么关系？你觉得有问题可以提个pr什么的

**Comment by jhwsx** [comment]
好的
