### ISSUE TITLE
拦截ams是跨进程的吗？

### ISSUE THREAD

**Issue by hhhaiai** [tiann/understand-plugin-framework#4]
ams-pms-hook 的拦截top界面，是跨进程的，如何实现跨进程的呢？

**Comment by tiann** [comment]
@hhhaiai 只能在自己app里面创建出来的进程才有效；自己指定的进程，每一个进程创建的时候都会执行Application里面的attachBaseContext以及onCreate系列方法；在这里可以进行Hook。

**Comment by hhhaiai** [comment]
@tiann   有没有办法获取其他进程的,以service哪种形式去拦截

**Comment by tiann** [comment]
@hhhaiai 除非root，不然这样安全性何在？
