### ISSUE TITLE
我想问个问题什么地方需要用HOOK

### ISSUE THREAD

**Issue by RichsJeson** [tiann/understand-plugin-framework#8]
Android本身就是插件化的体系，假设我有一个宿主APK-A，其它都是第三方的APP -C，那么我把C的所有so文件拷贝到A的so库存放的位置目录下，通过PackageManager的方式解析C包，再把C包里面的类存放到PackageInfo里面，剩下的就是当我要启动activity的时候，我通过proxyactivity的方式启动就行了，我不知道为啥需要HOOK？HOOK的本质是什么，有什么作用？

**Comment by tiann** [comment]
Hook就是把原有逻辑替换成自己想要的逻辑，仅此而已。没有什么需不需要，也谈不上本质；这只是一种手段而非目的，如果你不Hook也能达到目的（比如你说的用代理），那就不需要，并不是为了Hook而Hook。
区别就在于，Hook之后  你用跟原来相同的方式去使用某个东西，他的行为自动就发生了变化；就拿Activity插件来说，如果你不用Hook，那么通过startActivity启动插件Activity你必须指定proxyactivity或者让插件的Activity继承某个基类，或者你单独给一个方法 startPluginActivity；如果你替换掉了原本startActivity的逻辑（也就是Hook掉了）那使用者就不用关心是启动插件还是宿主了，对上层来说是透明的。

**Comment by RichsJeson** [comment]
但是HOOK也会影响性能吧

**Comment by alighters** [comment]
HOOK 只是启动 App 的时候 hook 一次，性能影响不大。最大的问题是就系统版本 API 发生变化时，需要做针对性的修改，还要考虑第三方自己ROM的影响

**Comment by tiann** [comment]
在Android上，兼容性问题并不是Hook的锅，你做别的也要面临这个问题。
而且系统版本发生变化，iOS，Mac，Linux都不能保证你不用做任何修改，遑论Android。

**Comment by kot32go** [comment]
建议看下博主的文章再提问：
http://weishu.me/2016/03/07/understand-plugin-framework-ams-pms-hook/
